FROM elixir:1.17-alpine

# Install build dependencies
RUN apk add --no-cache build-base git

WORKDIR /app

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set development environment
ENV MIX_ENV=dev

# Install dependencies
COPY mix.exs mix.lock ./
COPY config config
COPY apps apps

RUN mix deps.get
RUN mix deps.compile

# Start your application
CMD ["mix", "phx.server"]
